-- This SQL file is used to insert initial data into the database tables.

-- This SQL file is used to insert initial data into the database tables.
ALTER TABLE ecom_address
DROP CONSTRAINT FKG0DE3E6FIOYFH38D9X2T0L2PC;

ALTER TABLE ecom_address
ADD CONSTRAINT FKG0DE3E6FIOYFH38D9X2T0L2PC
FOREIGN KEY (user_id) REFERENCES ecom_user(id) ON DELETE CASCADE;

ALTER TABLE ecom_delivery_hub
DROP CONSTRAINT FKSJXCOEFV6DA11KP7VWBF512A6;

ALTER TABLE ecom_delivery_hub
ADD CONSTRAINT FKSJXCOEFV6DA11KP7VWBF512A6
FOREIGN KEY(address_id) REFERENCES ecom_address(id) ON DELETE CASCADE;

ALTER TABLE ecom_seller
DROP CONSTRAINT FK2YG5X9ETQ5Y6M2HE99JQUPCPG;

ALTER TABLE ecom_seller
ADD CONSTRAINT FK2YG5X9ETQ5Y6M2HE99JQUPCPG
FOREIGN KEY(address_id) REFERENCES ecom_address(id) ON DELETE CASCADE;

ALTER TABLE ecom_order_detail
DROP CONSTRAINT FKTGU8434SP17CMA5E4QYXITE5R;

ALTER TABLE ecom_order_detail
ADD CONSTRAINT FKTGU8434SP17CMA5E4QYXITE5R
FOREIGN KEY(product_id) REFERENCES ecom_product(id) ON DELETE CASCADE;

ALTER TABLE ecom_order
DROP CONSTRAINT FKJ2T2JQFAK1CQ970DHPAPJC74N;

ALTER TABLE ecom_order
ADD CONSTRAINT FKJ2T2JQFAK1CQ970DHPAPJC74N
FOREIGN KEY(user_id) REFERENCES ecom_user(id) ON DELETE CASCADE;

ALTER TABLE ecom_inventory
DROP CONSTRAINT FK7CITN3JF9VOCWUO76HI2OFPKK;

ALTER TABLE ecom_inventory
ADD CONSTRAINT FK7CITN3JF9VOCWUO76HI2OFPKK
FOREIGN KEY(product_id) REFERENCES ecom_product(id) ON DELETE CASCADE;